# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alfred Yu
email: yjb7049@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stay hungry, stay foolish
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://informatrix.github.io" # the base hostname & protocol for your site
github_username:  informatrix

# Build settings
#markdown: kramdown
#kramdown:
#  math_engine: mathjax
#markdown: redcarpet
markdown: kramdown
kramdown:
  math_engin: mathjax
highlighter: rough
